[project]
name = "gamecore"
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = []

[tool.setuptools.dynamic]
version = { attr = "tools.versioning.__version__" }

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
